name: Publish
env:
  HUSKY: 0
on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6

      - name: Install
        uses: ./.github/actions/install
      - name: Test
        run: pnpm run ci

      # Publish package
      - name: Publish
        shell: bash
        run: |
          npm publish --provenance --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
